server:
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8
  port: 8080

spring:
  datasource:
    username: C##scott
    password: 123456
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd HH:mm

mybatis-plus:
  type-aliases-package: com.isoftstone.oracleinterface.entity
  global-config:
    db-config:
      id-type: auto
      table-underline: true
